### ISSUE TITLE
Issue on import ipapi

### ISSUE THREAD

**Issue by cmallon** [ipapi-co/ipapi-python#1]
I'm using python 3.5.2 and Django 1.10. 

When trying to import ipapi it is throwing this error:
ImportError: cannot import name 'location'

Seems related to the __init__.py file.

**Comment by ipapi-co** [comment]
Thanks for reporting the issue with python 3. Release [0.5.2](https://github.com/ipapi-co/ipapi-python/tree/0.5.2) should fix it.
