### ISSUE TITLE
multiple fields

### ISSUE THREAD

**Issue by srulikuk** [ipapi-co/ipapi-python#3]
How can i get multiple fields in 1 request?
ipapi.location(ip='x.x.x.x', output='country, country_name')

**Comment by ipapi-co** [comment]
@srulikuk : 

`ipapi.location(ip='x.x.x.x')` will return multiple fields (in `JSON` format as default). You can disregard the ones you don't need. If you have follow up queries about the usage, please contact support at https://ipapi.co/contact/
