### ISSUE TITLE
Just a little question

### ISSUE THREAD

**Issue by msfcode** [ipapi-co/ipapi-python#4]
hello ... it is possible to use IPapi at Flask site ? who will collect the ip of people who open the site and send it to me ? thank you

**Comment by ipapi-co** [comment]
Yes, the API call is framework agnostic i.e. you can use it from any language or framework that supports an HTTPS request and can consume the response as JSON or CSV or XML or YAML. If the call is made from your backend server running flask, you'll have to pass the IP of your client in the URL. Please see [ipapi docs](https://ipapi.co/api). For any support related queries, you can reach out to us directly on our [support](https://ipapi.co/contact) page.
