### ISSUE TITLE
When I try 8.8.8.8 in python

### ISSUE THREAD

**Issue by pythonmobile** [ipapi-co/ipapi-python#6]
When I do: ipapi.location("8.8.8.8") - I get: 

{'asn': 'AS15169',
 'city': 'Mountain View',
 'continent_code': 'NA',
...
 'ip': '8.8.8.8',
 'latitude': 'Sign up to access',
 'longitude': 'Sign up to access',
 'message': 'Please message us at ipapi.co/trial for full access',
 'postal': 'Sign up to access',
}

Is it that the lat/lon are blocked in the free version? In the examples you show they are populated. Please fix this either in the documentation or the api?

**Comment by ipapi-co** [comment]
Hi @pythonmobile 

Thank you for pointing that out. We'll update the docs to make it consistent. The values should be accessible for most of the regions. Please drop us a message and we'll be happy to provide a trial account : https://ipapi.co/contact

**Comment by ipapi-co** [comment]
Hi @pythonmobile : Please try it out now and let us know if you face any issue.
